.ORIG x3000	;ADDRESS WHERE PROGRAM CODE BEGINS

	;R0: STORED VALUE OF X AND WHY AFTER FUNCTION EXECUTED
	;R1: VALUE OF X
	;R2: VALUE OF Y	
	LEA R0, xFF		;R0 IS LOADED WITH THE BEGINNING ADRESS OF THE DATA (x3100)	

	
	;storing first input digits
	LEA R0, DISPLAY1        ;LOAD THE ADDRESS OF THE "DISPLAY1" MESSAGE STRING
	PUTS			;PRINTS THE MESSAGE STRING
	GETC			;GET THE FIRST NUMBER
	OUT			;PRINTS THE FIRST NUMBER
	ADD R1, R0, x0		;STORES VALUE TO R1


	;storing second input digits
	LEA R0, DISPLAY2        ;LOAD THE ADDRESS OF THE "DISPLAY2" MESSAGE STRING	
	PUTS			;PRINTS THE MESSAGE STRING
	GETC			;GETS THE SECOND NUMBER
	OUT			;PRINTS THE SECOND NUMBER
	ADD R2, R0, x1		;STORES VALUE TO R2


	;ADDING TWO REGISTRIES 
	AND R3, R3, #0		;CLEAR REGISTRY R0
	LD R0, ADDING		;LOAD FUNCTION TO R0
	ADD R3, R1, R2		;ADD X + Y 
	ADD R0, R3, x2		;PLACES SUM OF R1 AND R2 INTO R0
	OUT
	LEA R0, STRINGRESULT1	;LOADS STRINGRESULT1 INTO REGISTRY R0
	PUTS			;PRINTS STRINGRESULT1 TO SCREEN
	
	;ANDING TWO REGISTRIES
	AND R3, R3, #0		;CLEAR REGISTRY R0
	LD R0, ANDING		;LOAD FUNCTION TO R0
	AND R3, R1, R2		;X AND Y
	ADD R0, R3, x3
	OUT
	LEA R0, STRINGRESULT2	;LOADS STRINGRESULT2 INTO REGISTRY R0
	PUTS			;PRINTS STRINGRESULT2 TO SCREEN
	
	
	;ORING TWO REGISTRIES
	AND R3, R3, #0		;CLEAR REGISTRY R0
	LD R0, ORING		;LOAD FUNCTION TO R0
	NOT R1, R1		;R3 = R1 OR R2
	NOT R2, R2
	AND R3, R1, R2
	NOT R3, R3
	ADD R0, R3, x4
	OUT
	LEA R0, STRINGRESULT3	;LOADS STRINGRESULT3 INTO REGISTRY R0
	PUTS			;PRINTS STRINGRESULT3 TO SCREEN
	
	
	;NOT ONE REGISTRY(X)
	AND R3, R3, #0		;CLEAR REGISTRY R0
	LD R0, NOTX		;LOAD FUNCTION TO R0
	NOT R3, R1 		;R3 = NOT(R1)
	ADD R0, R3, x5
	OUT
	LEA R0, STRINGRESULT4	;LOADS STRINGRESULT4 INTO REGISTRY R0
	PUTS			;PRINTS STRINGRESULT4 TO SCREEN
	
	;NOT ONE REGISTRY(Y)
	AND R3, R3, #0		;CLEAR REGISTRY R0
	LD R0, NOTY		;LOAD FUNCTION TO R0
	NOT R3, R2		;R0 = NOT(R2)
	ADD R0, R3, x6
	OUT
	LEA R0, STRINGRESULT5	;LOADS STRINGRESULT5 INTO REGISTRY R0
	PUTS			;PRINTS STRINGRESULT5 TO SCREEN

	;R1(X) + 3
	AND R3, R3, #0		;CLEAR REGISTRY R0
	LD R0, ADDX		;LOAD FUNCTION TO R0
	ADD R3, R1, #3		;R0 = R1 + 3
	ADD R0, R3, x7
	OUT
	LEA R0, STRINGRESULT6	;LOADS STRINGRESULT6 INTO REGISTRY R0
	PUTS			;PRINTS STRINGRESULT6 TO SCREEN

	;R3(Y) - 3
	AND R3, R3, #0		;CLEAR REGISTRY R0
	LD R0, SUBY		;LOAD FUNCTION TO R0
	ADD R3, R2, #-3		;R0 = R2 - 3
	ADD R0, R3, x8
	OUT
	LEA R0, STRINGRESULT7	;LOADS STRINGRESULT7 INTO REGISTRY R0
	PUTS			;PRINTS STRINGRESULT7 TO SCREEN
		
		HALT
		
	ADDING        .FILL x3102
	ANDING        .FILL x3103
	ORING         .FILL x3104
	NOTX          .FILL x3105
	NOTY          .FILL x3106
	ADDX          .FILL x3107
	SUBY          .FILL x3108
	TRUEFALSE     .FILL x3109


	DISPLAY1 .STRINGZ "\nenter the 1st number: "
	DISPLAY2 .STRINGZ "\nenter the 2nd number: "
	STRINGRESULT1 .STRINGZ "\nResult for X + Y: "
	STRINGRESULT2 .STRINGZ "\nResult for X AND Y: "
	STRINGRESULT3 .STRINGZ "\nResult for X OR Y: "
	STRINGRESULT4 .STRINGZ "\nResult for NOT(X): "
	STRINGRESULT5 .STRINGZ "\nResult for NOT(Y): "
	STRINGRESULT6 .STRINGZ "\nResult for X + 3: "
	STRINGRESULT7 .STRINGZ "\nResult for Y - 3: "
	


.END
	

	
